<?php 
/**
 * Pricelists
 */
register_field_group(array (
	'id' => 'acf_prislistor',
	'title' => 'Prislistor',
	'fields' => array (
		array (
			'key' => 'field_54218eb5194e5',
			'label' => 'Hår titel',
			'name' => 'pricelist_hair_title',
			'type' => 'text',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'none',
			'maxlength' => '',
		),
		array (
			'key' => 'field_54218eee194e6',
			'label' => 'Prislista hår',
			'name' => 'pricelist_hair',
			'type' => 'repeater',
			'instructions' => 'Om du vill ändra ordningen så kan du klicka på siffran till vänster dra till den position du vill.',
			'sub_fields' => array (
				array (
					'key' => 'field_54218f1b194e7',
					'label' => 'Tjänst',
					'name' => 'pricelist_hair_service',
					'type' => 'text',
					'column_width' => 75,
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
				array (
					'key' => 'field_54218f55194e8',
					'label' => 'Pris',
					'name' => 'pricelist_hair_price',
					'type' => 'text',
					'column_width' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
			),
			'row_min' => '',
			'row_limit' => '',
			'layout' => 'table',
			'button_label' => 'Lägg till ny',
		),
		array (
			'key' => 'field_54218fec5df76',
			'label' => 'Naglar titel',
			'name' => 'pricelist_nails_title',
			'type' => 'text',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'none',
			'maxlength' => '',
		),
		array (
			'key' => 'field_542190125df77',
			'label' => 'Prislista naglar',
			'name' => 'pricelist_nails',
			'type' => 'repeater',
			'sub_fields' => array (
				array (
					'key' => 'field_5421902b5df78',
					'label' => 'Tjänst',
					'name' => 'pricelist_nails_service',
					'type' => 'text',
					'column_width' => 75,
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5421903c5df79',
					'label' => 'Pris',
					'name' => 'pricelist_nails_price',
					'type' => 'text',
					'column_width' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
			),
			'row_min' => '',
			'row_limit' => '',
			'layout' => 'table',
			'button_label' => 'Lägg till ny',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-tpl-prices.php',
				'order_no' => 0,
				'group_no' => 0,
			),
		),
	),
	'options' => array (
		'position' => 'acf_after_title',
		'layout' => 'default',
		'hide_on_screen' => array (
		),
	),
	'menu_order' => 0,
));